// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Iconfont: typeof import('./ui/components/Iconfont.vue')['default']
    Ironman: typeof import('./ui/components/Ironman.vue')['default']
    UniInput: typeof import('./ui/components/UniInput.vue')['default']
    UniTab: typeof import('./ui/components/UniTab.vue')['default']
  }
}

export { }
