// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoxItem: typeof import('./ui/components/Box/BoxItem.vue')['default']
    BoxList: typeof import('./ui/components/Box/BoxList.vue')['default']
    Iconfont: typeof import('./ui/components/Iconfont.vue')['default']
    Ironman: typeof import('./ui/components/Ironman.vue')['default']
    UniBtn: typeof import('./ui/components/UniBtn.vue')['default']
    UniDialog: typeof import('./ui/components/UniDialog.vue')['default']
    UniDoubleBtn: typeof import('./ui/components/UniDoubleBtn.vue')['default']
    UniInput: typeof import('./ui/components/UniInput.vue')['default']
    UniMsg: typeof import('./ui/components/UniMsg.vue')['default']
    UniTab: typeof import('./ui/components/UniTab.vue')['default']
    UniTextArea: typeof import('./ui/components/UniTextArea.vue')['default']
  }
}

export { }
